WORKDIR=core

include misc/mf-template.mk

core:concurrence.d buffer.d message.d command.d response.d fdutil.d globals.d \
     connection.d server.d client.d subscription.d slot_map.d slot_calc.d \
     proxy.d acceptor.d stats.d
	true
