WORKDIR=core

include misc/mf-template.mk

core:concurrence.d buffer.d command.d response.d fdutil.d connection.d server.d \
     client.d slot_map.d slot_calc.d proxy.d subscription.d exceptions.d \
     globals.d stats.d
	true
